name: cirgps
channels:
- pyg
- pytorch
- nvidia
- https://repo.anaconda.com/pkgs/main
- defaults
dependencies:
- pip=22.3.1
- pyg=2.3.1
- pip:
  - aiohttp==3.8.6
  - aiosignal==1.3.1
  - async-timeout==4.0.3
  - asynctest==0.13.0
  - attrs==24.2.0
  - axial-positional-embedding==0.2.1
  - click==8.1.7
  - docker-pycreds==0.4.0
  - einops==0.6.1
  - frozenlist==1.3.3
  - fsspec==2023.1.0
  - gitdb==4.0.11
  - gitpython==3.1.43
  - importlib-metadata==6.7.0
  - lightning-utilities==0.10.1
  - littleutils==0.2.2
  - local-attention==1.9.3
  - multidict==6.0.5
  - networkx==2.6.3
  - ogb==1.3.6
  - outdated==0.2.2
  - packaging==24.0
  - pandas==1.3.5
  - performer-pytorch==1.1.4
  - platformdirs==4.0.0
  - protobuf==4.24.4
  - pyg-lib==0.2.0+pt113cu117
  - python-dateutil==2.9.0.post0
  - pytorch-lightning==1.9.5
  - pytz==2024.2
  - pyyaml==6.0.1
  - sentry-sdk==2.17.0
  - setproctitle==1.3.3
  - smmap==5.0.1
  - tensorboardx==2.6.2.2
  - torch-cluster==1.6.1+pt113cu117
  - torch-scatter==2.1.1+pt113cu117
  - torch-sparse==0.6.17+pt113cu117
  - torchmetrics==0.11.4
  - typing-extensions==4.7.1
  - wandb==0.18.5
  - yacs==0.1.8
  - yarl==1.9.4
  - zipp==3.15.0
