out_dir: results
metric_best: accuracy
num_workers: 6
wandb:
  use: False
  project: SRAM_8T_digitized_timing_top_fast
dataset:
  format: SRAM
  name: 8T_digitized_timing_top_fast
  task: graph
  task_type: classification
  num_hops: 4
  split_mode: standard
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode
  node_encoder_num_types: 3
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 2
  edge_encoder_bn: False
  add_target_edges: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  layer_type: gineconv
  layers_pre_mp: 0
  layers_mp: 9
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 192  # `gt.dim_hidden` must match `gnn.dim_inner`
  residual: True
  act: relu
  dropout: 0.0
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0001
  max_epoch: 200
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5
