out_dir: results
metric_best: accuracy
num_workers: 6
wandb:
  use: False
  project: SRAM
dataset:
  format: SRAM
  name: sandwich+ultra8t+ssram+digtime
  # name: sandwich+digtime
  task: graph
  task_type: classification
  num_hops: 1
  split_mode: standard
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+SPD
  node_encoder_num_types: 3
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 8
  edge_encoder_bn: False
  # added by shan
  add_target_edges: True
  edge_negative_sampling_ratio: 0.5
  to_undirected: True
  shuffle_split: True
  num_sampler: 6
  sample_rate: 
  - 0.015
  - 0.02
  - 0.5
  - 1.0
prep:
  exp: True
  # exp_algorithm: 'Hamiltonian'
  exp_deg: 5
  use_exp_edges: False
  add_edge_index: True # Set True if you want to add real edges beside expander edges
  num_virt_node: 6 # Set True if you want to add global node connections beside expander edges
  dist_enable: False
posenc_SPD:
  enable: True
  max_dist: 350
  dim_pe: 72
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1, 20)
  model: Linear
  dim_pe: 36
  raw_norm_type: BatchNorm
# pretrained:
#   dir: /data1/shenshan/dgl/GraphGPS/results/sramL-aug-GPSexp-SPD+RWSE.round1
#   freeze_main: False
#   reset_prediction_head: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 2
  ckpt_best: True
  # checkpoint resume added by shan
  auto_resume: True
  # epoch_resume: 18
  ckpt_clean: False
model:
  type: MultiModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Exphormer
  layers: 6
  n_heads: 4
  dim_hidden: 144  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
  res_linear: False
gnn:
  head: san_graph_for_reg
  layers_pre_mp: 0
  layers_post_mp: 2  # Not used when `gnn.head: san_graph`
  dim_inner: 144  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
  cir_statis_proj: False
optim:
  clip_grad_norm: True
  clip_grad_norm_value: 5.0
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0002
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6
